# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'InvertedDuckling' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'JSONModel'

  # Pods for InvertedDuckling

  target 'InvertedDucklingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'InvertedDucklingUITests' do
    # Pods for testing
  end

end
